name: 每日自动抓取节点

on:
  schedule:
    - cron: "0 22 * * *" # 每天北京时间早上 6 点准时开炉
  workflow_dispatch: # 允许你随时手动点击运行

permissions:
  contents: write # 赋予流水线写代码的权限

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 搭建 Python 炼丹环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 运行爬虫抓取
        run: python spider.py

      - name: 打包生成订阅链接并推送
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 👇 防撞气囊：先检查有没有抓到东西，文件大于 0 字节才上传
          if [ -s sub.txt ]; then
            git add sub.txt
            git commit -m "自动更新节点" || echo "今日节点无变化"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          else
            echo "⚠️ 今天没抓到节点，不执行推送，任务和平结束。"
          fi
